apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  labels:
    k8s-app: rook
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 5s
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook
  namespaceSelector:
    matchNames:
      - rook
