apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
data:
  traefik.toml: |
    logLevel = "INFO"
    debug = false
    sendAnonymousUsage = false

    defaultEntryPoints = ["http", "https"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]

    [api]
    dashboard = true

    [ping]

    [kubernetes]

    [acme]
    email = ""
    storage = "/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    acmeLogging = true
      [acme.dnsChallenge]
        provider = "azure"
